// types to fetch account list
export const FETCH_ACCOUNTS = "ACCOUNT::FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "ACCOUNT::FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAIL = "ACCOUNT::FETCH_ACCOUNTS_FAIL";

// types to fetch transactions
export const FETCH_TRANSACTIONS = "ACCOUNT::FETCH_TRANSACTIONS";
export const FETCH_TRANSACTIONS_SUCCESS = "ACCOUNT::FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAIL = "ACCOUNT::FETCH_TRANSACTIONS_FAIL";

// types to fetch currencies
export const FETCH_CURRENCIES = "ACCOUNT::FETCH_CURRENCIES";
export const FETCH_CURRENCIES_SUCCESS = "ACCOUNT::FETCH_CURRENCIES_SUCCESS";
export const FETCH_CURRENCIES_FAIL = "ACCOUNT::FETCH_CURRENCIES_FAIL";
